// components/forms/ProjectForm.tsx
"use client";
import React, { useState, useEffect } from "react";
import { Button } from "@/components/ui/Button";
import { Project, ProjectFormData } from "@/lib/types";
import {
  Save,
  X,
  User,
  MapPin,
  Phone,
  Mail,
  Building,
  Check,
  Sparkles,
  AlertCircle,
} from "lucide-react";

interface SimplifiedProjectFormData {
  clientName: string;
  projectAddress: string;
  clientAddress: string;
  phoneNumber: string;
  email: string;
  projectType: string;
  sameAsProject: boolean;
}

interface ProjectFormProps {
  onSubmit: (data: ProjectFormData) => Promise<void>;
  onCancel: () => void;
  initialData?: Project;
  isLoading?: boolean;
}

interface ValidationError {
  field: string;
  message: string;
}

export default function ProjectForm({
  onSubmit,
  onCancel,
  initialData,
  isLoading = false,
}: ProjectFormProps) {
  const [formData, setFormData] = useState<SimplifiedProjectFormData>({
    clientName: initialData?.clientName || "",
    projectAddress: initialData?.projectAddress || "",
    clientAddress: initialData?.clientAddress || "",
    phoneNumber: initialData?.phoneNumber || "",
    email: initialData?.email || "",
    projectType: initialData?.projectType || "Residential",
    sameAsProject: false,
  });

  const [autoGeneratedProjectName, setAutoGeneratedProjectName] = useState("");
  const [projectName, setProjectName] = useState(initialData?.name || "");
  const [errors, setErrors] = useState<ValidationError[]>([]);
  const [touched, setTouched] = useState<Set<string>>(new Set());

  // Validation functions
  const validateClientName = (name: string): string | null => {
    const trimmed = name.trim();
    if (!trimmed) return "Client name is required";
    if (trimmed.length < 2) return "Client name must be at least 2 characters";
    if (trimmed.length > 100) return "Client name must be less than 100 characters";
    if (!/^[a-zA-Z\s\-\.\']+$/.test(trimmed)) return "Client name can only contain letters, spaces, hyphens, periods, and apostrophes";
    return null;
  };

  const validateProjectName = (name: string): string | null => {
    const trimmed = name.trim();
    if (!trimmed) return "Project name is required";
    if (trimmed.length < 2) return "Project name must be at least 2 characters";
    if (trimmed.length > 150) return "Project name must be less than 150 characters";
    return null;
  };

  const validateAddress = (address: string, fieldName: string): string | null => {
    const trimmed = address.trim();
    if (!trimmed) return `${fieldName} is required`;
    if (trimmed.length < 10) return `${fieldName} must be at least 10 characters`;
    if (trimmed.length > 300) return `${fieldName} must be less than 300 characters`;
    return null;
  };

  const validatePhoneNumber = (phone: string): string | null => {
    const trimmed = phone.trim();
    if (!trimmed) return "Phone number is required";
    
    // Remove all non-digit characters for validation
    const digitsOnly = trimmed.replace(/\D/g, '');
    
    if (digitsOnly.length < 10) return "Phone number must be at least 10 digits";
    if (digitsOnly.length > 15) return "Phone number must be less than 15 digits";
    
    // Basic phone number format validation (supports international formats)
    const phoneRegex = /^[\+]?[\d\s\-\(\)\.]{10,20}$/;
    if (!phoneRegex.test(trimmed)) return "Please enter a valid phone number";
    
    return null;
  };

  const validateEmail = (email: string): string | null => {
    const trimmed = email.trim();
    if (!trimmed) return null; // Email is optional
    
    if (trimmed.length > 254) return "Email address is too long";
    
    const emailRegex = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;
    if (!emailRegex.test(trimmed)) return "Please enter a valid email address";
    
    return null;
  };

  // Real-time validation
  const validateForm = (): ValidationError[] => {
    const newErrors: ValidationError[] = [];

    // Validate client name
    const clientNameError = validateClientName(formData.clientName);
    if (clientNameError) newErrors.push({ field: 'clientName', message: clientNameError });

    // Validate project name
    const projectNameError = validateProjectName(projectName);
    if (projectNameError) newErrors.push({ field: 'projectName', message: projectNameError });

    // Validate project address
    const projectAddressError = validateAddress(formData.projectAddress, 'Project address');
    if (projectAddressError) newErrors.push({ field: 'projectAddress', message: projectAddressError });

    // Validate client address
    const clientAddressError = validateAddress(formData.clientAddress, 'Client address');
    if (clientAddressError) newErrors.push({ field: 'clientAddress', message: clientAddressError });

    // Validate phone number
    const phoneError = validatePhoneNumber(formData.phoneNumber);
    if (phoneError) newErrors.push({ field: 'phoneNumber', message: phoneError });

    // Validate email (only if provided)
    const emailError = validateEmail(formData.email);
    if (emailError) newErrors.push({ field: 'email', message: emailError });

    return newErrors;
  };

  // Get error for specific field
  const getFieldError = (fieldName: string): string | null => {
    const error = errors.find(err => err.field === fieldName);
    return error ? error.message : null;
  };

  // Check if field has error and is touched
  const hasFieldError = (fieldName: string): boolean => {
    return touched.has(fieldName) && !!getFieldError(fieldName);
  };

  // Mark field as touched
  const markFieldTouched = (fieldName: string) => {
    setTouched(prev => new Set(prev).add(fieldName));
  };

  // Update validation when form data changes
  useEffect(() => {
    const newErrors = validateForm();
    setErrors(newErrors);
  }, [formData, projectName]);

  // Auto-generate project name when client name changes
  useEffect(() => {
    if (formData.clientName.trim()) {
      const generated = `${formData.clientName.trim()} Project`;
      setAutoGeneratedProjectName(generated);

      // Only auto-set if user hasn't manually edited the project name
      if (!projectName || projectName === autoGeneratedProjectName) {
        setProjectName(generated);
      }
    } else {
      setAutoGeneratedProjectName("");
      if (projectName === autoGeneratedProjectName) {
        setProjectName("");
      }
    }
  }, [formData.clientName]);

  // Handle same as project address checkbox
  useEffect(() => {
    if (formData.sameAsProject && formData.projectAddress) {
      setFormData((prev) => ({
        ...prev,
        clientAddress: formData.projectAddress,
      }));
    }
  }, [formData.sameAsProject, formData.projectAddress]);

  const handleInputChange = (
    field: keyof SimplifiedProjectFormData,
    value: any
  ) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const handleSameAsProjectChange = (checked: boolean) => {
    setFormData((prev) => ({
      ...prev,
      sameAsProject: checked,
      clientAddress: checked ? formData.projectAddress : "",
    }));
    
    // Clear client address error if using same as project
    if (checked) {
      setTouched(prev => {
        const newTouched = new Set(prev);
        newTouched.delete('clientAddress');
        return newTouched;
      });
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Mark all fields as touched for validation display
    const allFields = ['clientName', 'projectName', 'projectAddress', 'clientAddress', 'phoneNumber', 'email'];
    setTouched(new Set(allFields));

    // Validate form
    const validationErrors = validateForm();
    if (validationErrors.length > 0) {
      // Focus on first error field
      const firstErrorField = validationErrors[0].field;
      const element = document.querySelector(`[name="${firstErrorField}"]`) as HTMLElement;
      if (element) {
        element.focus();
        element.scrollIntoView({ behavior: 'smooth', block: 'center' });
      }
      return;
    }

    // Transform simplified form data to full ProjectFormData
    const fullProjectData: ProjectFormData = {
      name: projectName.trim(),
      clientName: formData.clientName.trim(),
      clientAddress: formData.clientAddress.trim(),
      projectAddress: formData.projectAddress.trim(),
      phoneNumber: formData.phoneNumber.trim(),
      email: formData.email.trim(),
      projectType: formData.projectType,
      // Set reasonable defaults for fields not in the simplified form
      agreementDate: new Date().toISOString().split("T")[0], // Today's date
      numberOfFloors: 1,
      projectDuration: 6,
      estimatedBudget: 0,
      status: "New",
    };

    await onSubmit(fullProjectData);
  };

  const projectTypes = [
    "Residential",
    "Commercial",
    "Industrial",
    "Institutional",
    "Interior Fit-out",
    "Other"
  ];

  // Check if form is valid
  const isFormValid = errors.length === 0 && projectName.trim() !== '';

  // Error message component
  const ErrorMessage = ({ message }: { message: string }) => (
    <div className="flex items-center mt-2 text-red-600 text-sm">
      <AlertCircle className="h-4 w-4 mr-1 flex-shrink-0" />
      <span>{message}</span>
    </div>
  );

  return (
    <div className=" py-8 px-4 h-full overflow-y-auto">
      <div className="bg-white rounded-2xl border border-gray-200/60 shadow-xl shadow-blue-100/50 backdrop-blur-sm ">
        <form
          onSubmit={handleSubmit}
          className="p-8 space-y-8 overflow-y-auto h-full"
          noValidate
        >
          {/* Client Name - Enhanced Important Field */}
          <div className="group">
            <label className="flex items-center text-sm font-semibold text-gray-800 mb-3">
              <div className="p-2 bg-blue-100 rounded-lg mr-3 group-focus-within:bg-blue-200 transition-colors">
                <User className="h-4 w-4 text-blue-600" />
              </div>
              Client Full Name *
            </label>
            <input
              type="text"
              name="clientName"
              value={formData.clientName}
              onChange={(e) => handleInputChange("clientName", e.target.value)}
              onBlur={() => markFieldTouched('clientName')}
              className={`w-full px-5 py-4 border-2 rounded-xl focus:outline-none transition-all duration-200 text-gray-900 placeholder-gray-400 bg-gray-50/50 hover:bg-white ${
                hasFieldError('clientName')
                  ? 'border-red-300 focus:ring-4 focus:ring-red-500/20 focus:border-red-500'
                  : 'border-gray-200 focus:ring-4 focus:ring-blue-500/20 focus:border-blue-500'
              }`}
              placeholder="Enter client's full name"
              required
              autoFocus
              maxLength={100}
            />
            {hasFieldError('clientName') && <ErrorMessage message={getFieldError('clientName')!} />}
          </div>

          {/* Enhanced Auto-generated Project Name */}
          <div className="group">
            <label className="flex items-center text-sm font-semibold text-gray-800 mb-3">
              <div className="p-2 bg-emerald-100 rounded-lg mr-3 group-focus-within:bg-emerald-200 transition-colors">
                <Building className="h-4 w-4 text-emerald-600" />
              </div>
              Project Name *
            </label>
            <input
              type="text"
              name="projectName"
              value={projectName}
              onChange={(e) => setProjectName(e.target.value)}
              onBlur={() => markFieldTouched('projectName')}
              className={`w-full px-5 py-4 border-2 rounded-xl focus:outline-none transition-all duration-200 text-gray-900 placeholder-gray-400 bg-gray-50/50 hover:bg-white ${
                hasFieldError('projectName')
                  ? 'border-red-300 focus:ring-4 focus:ring-red-500/20 focus:border-red-500'
                  : 'border-gray-200 focus:ring-4 focus:ring-emerald-500/20 focus:border-emerald-500'
              }`}
              placeholder="Project name will auto-generate"
              maxLength={150}
            />
            {hasFieldError('projectName') && <ErrorMessage message={getFieldError('projectName')!} />}
            {autoGeneratedProjectName &&
              projectName !== autoGeneratedProjectName && (
                <button
                  type="button"
                  onClick={() => setProjectName(autoGeneratedProjectName)}
                  className="inline-flex items-center text-sm text-blue-600 hover:text-blue-700 mt-2 px-3 py-1 bg-blue-50 hover:bg-blue-100 rounded-lg transition-colors duration-200"
                >
                  <Sparkles className="h-3 w-3 mr-1" />
                  Use suggested: "{autoGeneratedProjectName}"
                </button>
              )}
          </div>

          {/* Enhanced Project Address */}
          <div className="group">
            <label className="flex items-center text-sm font-semibold text-gray-800 mb-3">
              <div className="p-2 bg-orange-100 rounded-lg mr-3 group-focus-within:bg-orange-200 transition-colors">
                <MapPin className="h-4 w-4 text-orange-600" />
              </div>
              Project Address *
            </label>
            <textarea
              name="projectAddress"
              value={formData.projectAddress}
              onChange={(e) =>
                handleInputChange("projectAddress", e.target.value)
              }
              onBlur={() => markFieldTouched('projectAddress')}
              className={`w-full px-5 py-4 border-2 rounded-xl focus:outline-none transition-all duration-200 text-gray-900 placeholder-gray-400 bg-gray-50/50 hover:bg-white resize-none ${
                hasFieldError('projectAddress')
                  ? 'border-red-300 focus:ring-4 focus:ring-red-500/20 focus:border-red-500'
                  : 'border-gray-200 focus:ring-4 focus:ring-orange-500/20 focus:border-orange-500'
              }`}
              placeholder="Enter the project site address"
              rows={3}
              required
              maxLength={300}
            />
            {hasFieldError('projectAddress') && <ErrorMessage message={getFieldError('projectAddress')!} />}
          </div>

          {/* Enhanced Client Address with Improved Checkbox */}
          <div className="group">
            <label className="flex items-center text-sm font-semibold text-gray-800 mb-3">
              <div className="p-2 bg-purple-100 rounded-lg mr-3 group-focus-within:bg-purple-200 transition-colors">
                <MapPin className="h-4 w-4 text-purple-600" />
              </div>
              Client Address *
            </label>

            {/* Enhanced Same as Project Checkbox */}
            <div className="mb-4">
              <label className="flex items-center cursor-pointer group/checkbox p-3 rounded-xl hover:bg-gray-50 transition-colors duration-200">
                <input
                  type="checkbox"
                  checked={formData.sameAsProject}
                  onChange={(e) => handleSameAsProjectChange(e.target.checked)}
                  className="sr-only"
                />
                <div
                  className={`w-6 h-6 border-2 rounded-lg flex items-center justify-center mr-3 transition-all duration-200 ${
                    formData.sameAsProject
                      ? "bg-gradient-to-br from-blue-500 to-blue-600 border-blue-500 shadow-lg shadow-blue-500/25"
                      : "border-gray-300 hover:border-gray-400 group-hover/checkbox:border-blue-300"
                  }`}
                >
                  {formData.sameAsProject && (
                    <Check className="h-4 w-4 text-white" />
                  )}
                </div>
                <span className="text-sm font-medium text-gray-700 group-hover/checkbox:text-gray-900">
                  Same as project address
                </span>
              </label>
            </div>

            <textarea
              name="clientAddress"
              value={formData.clientAddress}
              onChange={(e) =>
                handleInputChange("clientAddress", e.target.value)
              }
              onBlur={() => !formData.sameAsProject && markFieldTouched('clientAddress')}
              className={`w-full px-5 py-4 border-2 rounded-xl focus:outline-none transition-all duration-200 text-gray-900 placeholder-gray-400 resize-none ${
                formData.sameAsProject
                  ? "border-gray-200 bg-gray-100 cursor-not-allowed opacity-60"
                  : hasFieldError('clientAddress')
                  ? "border-red-300 focus:ring-4 focus:ring-red-500/20 focus:border-red-500 bg-gray-50/50 hover:bg-white"
                  : "border-gray-200 focus:ring-4 focus:ring-purple-500/20 focus:border-purple-500 bg-gray-50/50 hover:bg-white"
              }`}
              placeholder="Enter client's address"
              rows={3}
              required
              disabled={formData.sameAsProject}
              maxLength={300}
            />
            {!formData.sameAsProject && hasFieldError('clientAddress') && <ErrorMessage message={getFieldError('clientAddress')!} />}
          </div>

          {/* Enhanced Contact Information Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="group">
              <label className="flex items-center text-sm font-semibold text-gray-800 mb-3">
                <div className="p-2 bg-green-100 rounded-lg mr-3 group-focus-within:bg-green-200 transition-colors">
                  <Phone className="h-4 w-4 text-green-600" />
                </div>
                Phone Number *
              </label>
              <input
                type="tel"
                name="phoneNumber"
                value={formData.phoneNumber}
                onChange={(e) =>
                  handleInputChange("phoneNumber", e.target.value)
                }
                onBlur={() => markFieldTouched('phoneNumber')}
                className={`w-full px-5 py-4 border-2 rounded-xl focus:outline-none transition-all duration-200 text-gray-900 placeholder-gray-400 bg-gray-50/50 hover:bg-white ${
                  hasFieldError('phoneNumber')
                    ? 'border-red-300 focus:ring-4 focus:ring-red-500/20 focus:border-red-500'
                    : 'border-gray-200 focus:ring-4 focus:ring-green-500/20 focus:border-green-500'
                }`}
                placeholder="Enter phone number"
                required
                maxLength={20}
              />
              {hasFieldError('phoneNumber') && <ErrorMessage message={getFieldError('phoneNumber')!} />}
            </div>

            <div className="group">
              <label className="flex items-center text-sm font-semibold text-gray-800 mb-3">
                <div className="p-2 bg-pink-100 rounded-lg mr-3 group-focus-within:bg-pink-200 transition-colors">
                  <Mail className="h-4 w-4 text-pink-600" />
                </div>
                Email{" "}
                <span className="text-gray-500 font-normal">(Optional)</span>
              </label>
              <input
                type="email"
                name="email"
                value={formData.email}
                onChange={(e) => handleInputChange("email", e.target.value)}
                onBlur={() => markFieldTouched('email')}
                className={`w-full px-5 py-4 border-2 rounded-xl focus:outline-none transition-all duration-200 text-gray-900 placeholder-gray-400 bg-gray-50/50 hover:bg-white ${
                  hasFieldError('email')
                    ? 'border-red-300 focus:ring-4 focus:ring-red-500/20 focus:border-red-500'
                    : 'border-gray-200 focus:ring-4 focus:ring-pink-500/20 focus:border-pink-500'
                }`}
                placeholder="Enter email address"
                maxLength={254}
              />
              {hasFieldError('email') && <ErrorMessage message={getFieldError('email')!} />}
            </div>
          </div>

          {/* Enhanced Project Type */}
          <div className="group">
            <label className="flex items-center text-sm font-semibold text-gray-800 mb-3">
              <div className="p-2 bg-indigo-100 rounded-lg mr-3 group-focus-within:bg-indigo-200 transition-colors">
                <Building className="h-4 w-4 text-indigo-600" />
              </div>
              Project Type{" "}
              <span className="text-gray-500 font-normal">(Optional)</span>
            </label>
            <select
              name="projectType"
              value={formData.projectType}
              onChange={(e) => handleInputChange("projectType", e.target.value)}
              className="w-full px-5 py-4 border-2 border-gray-200 rounded-xl focus:outline-none focus:ring-4 focus:ring-indigo-500/20 focus:border-indigo-500 transition-all duration-200 text-gray-900 bg-gray-50/50 hover:bg-white cursor-pointer"
            >
              {projectTypes.map((type) => (
                <option key={type} value={type}>
                  {type}
                </option>
              ))}
            </select>
            <p className="text-xs text-gray-500 mt-2 px-1">
              You can always change this later when creating estimates
            </p>
          </div>

          {/* Enhanced Form Actions */}
          <div className="flex justify-end space-x-4 pt-6 border-t border-gray-100">
            <Button
              type="button"
              variant="outline"
              onClick={onCancel}
              disabled={isLoading}
              className="px-8 py-3 border-2 border-gray-300 hover:border-gray-400 hover:bg-gray-50 rounded-xl font-medium transition-all duration-200"
            >
              <X className="h-4 w-4 mr-2" />
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={isLoading || !isFormValid}
              className={`px-8 py-3 rounded-xl font-semibold shadow-lg transition-all duration-200 ${
                isFormValid && !isLoading
                  ? 'bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white shadow-blue-500/25 hover:shadow-blue-500/40'
                  : 'bg-gray-300 text-gray-500 cursor-not-allowed shadow-gray-300/25'
              }`}
            >
              {isLoading ? (
                <div className="animate-spin rounded-full h-4 w-4 border-2 border-white/30 border-t-white mr-2" />
              ) : (
                <Save className="h-4 w-4 mr-2" />
              )}
              {initialData ? "Update Project" : "Create Project"}
            </Button>
          </div>
        </form>
      </div>

      {/* Enhanced Footer with Better Styling */}
      <div className="mt-6 text-center">
        <div className="inline-flex items-center px-4 py-2 bg-white/60 backdrop-blur-sm rounded-full border border-gray-200/60">
          <div className="w-2 h-2 bg-blue-500 rounded-full mr-3 animate-pulse"></div>
          <p className="text-sm text-gray-600 font-medium">
            Details like budget, timeline, and agreements can be added later
            when creating estimates
          </p>
        </div>
      </div>
    </div>
  );
}